version: 2.1
jobs:
  build:
    working_directory: ~/cours-l2
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: test
          command: yarn && yarn global add jest && yarn test
      - store_artifacts:
          path: test-results.xml
          prefix: tests